apiVersion: v1
kind: Namespace
metadata:
  name: omaticaya
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: omaticaya-cr
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - delete
      - get
      - list
      - watch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: omaticaya-sa
  namespace: omaticaya
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: omaticaya-crb
  namespace: omaticaya
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: omaticaya-cr
subjects:
  - kind: ServiceAccount
    name: omaticaya-sa
    namespace: omaticaya
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: omaticaya
  namespace: omaticaya
  labels:
    app: omaticaya
spec:
  selector:
    matchLabels:
      app: omaticaya
  template:
    metadata:
      labels:
        app: omaticaya
    spec:
      serviceAccountName: omaticaya-sa
      containers:
        - name: omaticaya
          image: hyc3z/omaticaya:cuda-10.1-c
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: SCHEDULING_POLICY
              value: "default"
            - name: MONITOR_GPU_INTERVAL_PATTERN
              value: "*/5 * * * * ?"
            - name: MONITOR_POLICY_INTERVAL_PATTERN
              value: "0 * * * * ?"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      terminationGracePeriodSeconds: 30